"""empty message

Revision ID: 09b76541f980
Revises: 25d12119d4b9
Create Date: 2024-08-04 11:13:51.355673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b76541f980'
down_revision = '25d12119d4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pLocation_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pLocation_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pLocation_lng')
        batch_op.drop_column('pLocation_lat')

    # ### end Alembic commands ###
