"""db update

Revision ID: 25d12119d4b9
Revises: 5817d04f10e5
Create Date: 2024-08-04 11:00:09.299625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d12119d4b9'
down_revision = '5817d04f10e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pAge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pField', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pLocation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pGoals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pQualities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pQualities')
        batch_op.drop_column('pGoals')
        batch_op.drop_column('pLocation')
        batch_op.drop_column('pField')
        batch_op.drop_column('pAge')

    # ### end Alembic commands ###
