"""profile addition

Revision ID: e3241f68d41f
Revises: 458c3b5b947e
Create Date: 2024-08-03 15:10:14.308074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3241f68d41f'
down_revision = '458c3b5b947e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('self_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strength', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('goals', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('goals')
        batch_op.drop_column('strength')
        batch_op.drop_column('experience')
        batch_op.drop_column('self_description')
        batch_op.drop_column('location')
        batch_op.drop_column('field')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
